name: ClashOfBlocks
version: 1.0
authors: [Aperx, Stilldabomb, mineu999, Not2EXceL, DevRosemberg]
description: A Clash of Clans, a popular iOS/Android game, inspired plugin.
main: com.github.cob.ClashOfBlocks

commands:
  help:
    permission: none.none
 